// console.log('hello');
var fullName = 'John Doe';
var isCool = true;
var totalPets = 2;
console.log('value of fullName:', fullName);
console.log('value of isCool:', isCool);
console.log('value of totalPets:', totalPets);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
var unknown = null;
console.log('value of unknown:', unknown);
console.log('typeof unknown:', unknown);
// console.log('hello');
var never = undefined;
console.log('value of never:', never);
console.log('typeof never:', never);
